# Generated by Django 5.1.3 on 2024-12-21 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcv.contact'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcv.personne'),
        ),
    ]
