# Generated by Django 5.1.3 on 2024-12-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcv', '0002_alter_cv_contact_alter_cv_personne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
