# Generated by Django 5.1.3 on 2024-12-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcv', '0003_alter_formation_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='design',
            field=models.CharField(choices=[('design1', 'Design 1'), ('design2', 'Design 2'), ('design3', 'Design 3'), ('design4', 'Design 4')], default='design1', max_length=10),
        ),
        migrations.AddField(
            model_name='cv',
            name='title',
            field=models.CharField(default='CV sans titre', max_length=100),
        ),
    ]
